Repository flux-framework/flux-accounting, pull requests merged in 2020-12, with the labels that each got.

#73 build: convert python code and tests over to autotools, TAP, and sharness
  .gitignore
  INSTALL
  Makefile.am
  accounting/__init__.py
  config/adl_recursive_eval.m4
  config/am_check_pymod.m4
  config/ax_python_devel.m4
  config/tap-driver.py
  config/tap-driver.sh
  configure.ac
  requirements.txt
  setup.py
  src/Makefile.am
  src/bindings/Makefile.am
  src/bindings/python/Makefile.am
  src/bindings/python/flux/Makefile.am
  src/bindings/python/flux/accounting/.gitignore
  src/bindings/python/flux/accounting/Makefile.am
  src/bindings/python/flux/accounting/__init__.py.in
  src/bindings/python/flux/accounting/accounting_cli_functions.py
  src/bindings/python/flux/accounting/create_db.py
  src/bindings/python/flux/accounting/flux-account.py
  src/bindings/python/flux/accounting/job_archive_interface.py
  src/bindings/python/flux/accounting/print_hierarchy.py
  src/bindings/python/flux/accounting/test/test_bank_subcommands.py
  src/bindings/python/flux/accounting/test/test_create_db.py
  src/bindings/python/flux/accounting/test/test_example.py
  src/bindings/python/flux/accounting/test/test_job_archive_interface.py
  src/bindings/python/flux/accounting/test/test_user_subcommands.py
  src/fairness/print_hierarchy/Makefile.am
  src/fairness/print_hierarchy/test-print-hierarchy.sh
  src/fairness/weighted_tree/test/Makefile.am
  src/fairness/weighted_tree/test/weighted_tree_test01.cpp
  src/test/docker/centos8/Dockerfile.centos8
  src/test/docker/ubuntu/Dockerfile.ubuntu
  t/Makefile.am
  t/aggregate-results.sh
  t/pycotap/.gitignore
  t/pycotap/.travis.yml
  t/pycotap/COPYING
  t/pycotap/README.md
  t/pycotap/example/test_example.py
  t/pycotap/pycotap/__init__.py
  t/pycotap/setup.py
  t/pycotap/test/test.py
  t/scripts/run_timeout.py
  t/sharness.d/01-setup.sh
  t/sharness.d/flux-sharness.sh
  t/sharness.sh
  t/t0000-sharness.t
  t/t1000-print-hierarchy.t
  t/test-terminal.perl
  test/__init__.py
  tox.ini
Labels: merge-when-passing

#80 t0000-sharness.sh: fix test with debug/verbose set in env
  t/t0000-sharness.t
Labels: merge-when-passing

#78 delete_bank(): make function recursive
  src/bindings/python/flux/accounting/accounting_cli_functions.py
  src/bindings/python/flux/accounting/test/test_bank_subcommands.py
Labels: enhancement, merge-when-passing

#79 fairshare implementation part 1: add effective job usage factor calculation
  src/bindings/python/flux/accounting/README.md
  src/bindings/python/flux/accounting/accounting_cli_functions.py
  src/bindings/python/flux/accounting/create_db.py
  src/bindings/python/flux/accounting/flux-account.py
  src/bindings/python/flux/accounting/job_archive_interface.py
  src/bindings/python/flux/accounting/print_hierarchy.py
  src/bindings/python/flux/accounting/test/test_create_db.py
  src/bindings/python/flux/accounting/test/test_job_archive_interface.py
  src/bindings/python/flux/accounting/test/test_user_subcommands.py
  src/fairness/print_hierarchy/print_hierarchy.cpp
  t/t1000-print-hierarchy.t
Labels: enhancement, merge-when-passing

#88 NEWS.md: add release notes for v0.5.0
  NEWS.md
Labels: documentation, merge-when-passing

#90 repo: remove unused imports, variable in accounting/, change license in fairness/ to LGPL
  AUTHORS
  COPYING
  LICENSE
  src/bindings/python/flux/accounting/accounting_cli_functions.py
  src/bindings/python/flux/accounting/create_db.py
  src/bindings/python/flux/accounting/job_archive_interface.py
  src/bindings/python/flux/accounting/print_hierarchy.py
  src/fairness/account/account.cpp
  src/fairness/account/account.hpp
  src/fairness/weighted_tree/weighted_tree.cpp
  src/fairness/weighted_tree/weighted_tree.hpp
  src/fairness/weighted_tree/weighted_walk.cpp
  src/fairness/weighted_tree/weighted_walk.hpp
Labels: documentation, improvement, merge-when-passing
