Repository flux-framework/flux-accounting, pull requests merged in 2020-11, with the labels that each got.

#65 Add library that provides a weighted tree-based fairness
  ChangeLog
  DISCLAIMER.LLNS
  Makefile.am
  Makefile.orig
  NEWS
  README
  autogen.sh
  config/ax_code_coverage.m4
  config/ax_cxx_compile_stdcxx.m4
  config/ax_flux_core.m4
  config/tap-driver.sh
  configure.ac
  src/Makefile.am
  src/common/Makefile.am
  src/common/libtap/Makefile.am
  src/common/libtap/tap.c
  src/common/libtap/tap.h
  src/fairness/Makefile.am
  src/fairness/account/account.cpp
  src/fairness/account/account.hpp
  src/fairness/weighted_tree/Makefile.am
  src/fairness/weighted_tree/test/Makefile.am
  src/fairness/weighted_tree/test/accounts_data/minimal.csv
  src/fairness/weighted_tree/test/accounts_data/small_no_tie.csv
  src/fairness/weighted_tree/test/accounts_data/small_tie.csv
  src/fairness/weighted_tree/test/accounts_data/small_tie_all.csv
  src/fairness/weighted_tree/test/accounts_data/small_tie_diff_type.csv
  src/fairness/weighted_tree/test/accounts_data/small_zero_shares.csv
  src/fairness/weighted_tree/test/weighted_tree_load.cpp
  src/fairness/weighted_tree/test/weighted_tree_load.hpp
  src/fairness/weighted_tree/test/weighted_tree_test01.cpp
  src/fairness/weighted_tree/weighted_tree.cpp
  src/fairness/weighted_tree/weighted_tree.hpp
  src/fairness/weighted_tree/weighted_walk.cpp
  src/fairness/weighted_tree/weighted_walk.hpp
Labels: merge-when-passing

#49 edit error handling in create-db(), edit-user()
  accounting/accounting_cli.py
  accounting/accounting_cli_functions.py
  accounting/create_db.py
  accounting/print_hierarchy.py
  test/test_bank_subcommands.py
  test/test_user_subcommands.py
Labels: improvement, merge-when-passing

#64 add print_hierarchy() C++ implementation to weighted tree lib
  .gitignore
  accounting/accounting_cli.py
  accounting/create_db.py
  configure.ac
  src/fairness/Makefile.am
  src/fairness/print_hierarchy/Makefile.am
  src/fairness/print_hierarchy/print_hierarchy.cpp
  src/fairness/print_hierarchy/test-print-hierarchy.sh
Labels: merge-when-passing

#68 NEWS.md: add release notes for v0.4.0
  NEWS.md
Labels: documentation, merge-when-passing

#72 print_hierarchy.cpp: move global variables into main(), add another test
  src/fairness/print_hierarchy/print_hierarchy.cpp
  src/fairness/print_hierarchy/test-print-hierarchy.sh
Labels: improvement, merge-when-passing
