Repository flux-framework/flux-accounting, pull requests merged in 2021-07, with the labels that each got.

#124 association_table: remove unused fields
  src/bindings/python/fluxacct/accounting/accounting_cli_functions.py
  src/bindings/python/fluxacct/accounting/create_db.py
  src/bindings/python/fluxacct/accounting/test/test_create_db.py
  src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
Labels: improvement, merge-when-passing

#126 python: break up accounting_cli_functions.py
  src/bindings/python/fluxacct/accounting/Makefile.am
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
  src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
  src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account.py
Labels: improvement, merge-when-passing

#122 plugin: add multifactor priority plugin
  .github/workflows/main.yml
  configure.ac
  src/Makefile.am
  src/bindings/python/fluxacct/accounting/create_db.py
  src/bindings/python/fluxacct/accounting/job_archive_interface.py
  src/bindings/python/fluxacct/accounting/test/test_create_db.py
  src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
  src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account.py
  src/plugins/Makefile.am
  src/plugins/bulk_update.py
  src/plugins/mf_priority.cpp
  src/test/checks-annotate.sh
  src/test/docker/bionic/Dockerfile
  src/test/docker/centos8/Dockerfile
  t/Makefile.am
  t/rc/rc1-job
  t/rc/rc1-kvs
  t/rc/rc3-job
  t/rc/rc3-kvs
  t/sharness.d/flux-sharness.sh
  t/t1001-mf-priority.t
Labels: enhancement, merge-when-passing

#129 t: add multi-factor priority order sharness tests
  t/Makefile.am
  t/scripts/send_payload.py
  t/scripts/submit_as.py
  t/t1001-mf-priority-basic.t
  t/t1002-mf-priority-small-no-tie.t
  t/t1003-mf-priority-small-tie.t
  t/t1004-mf-priority-small-tie-all.t
Labels: enhancement, merge-when-passing

#132 plugins: fix several typos
  src/plugins/mf_priority.cpp
Labels: merge-when-passing

#130 association_table: add "default_bank" column, change plugin's default bank behavior
  src/bindings/python/fluxacct/accounting/create_db.py
  src/bindings/python/fluxacct/accounting/test/test_create_db.py
  src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/plugins/bulk_update.py
  src/plugins/mf_priority.cpp
  t/t1001-mf-priority-basic.t
  t/t1002-mf-priority-small-no-tie.t
  t/t1003-mf-priority-small-tie.t
  t/t1004-mf-priority-small-tie-all.t
Labels: enhancement, improvement, merge-when-passing
