Repository flux-framework/flux-accounting, pull requests merged in 2021-11, with the labels that each got.

#171 cmd: unify optional path argument
  src/cmd/flux_account_update_fshare.cpp
  src/fairness/print_hierarchy/flux_account_shares.cpp
  t/expected/help_message.txt
  t/t1000-print-hierarchy.t
  t/t1006-update-fshare.t
Labels: merge-when-passing, improvement

#170 database: change default DB path, update README build instructions
  README.md
  src/bindings/python/fluxacct/accounting/__init__.py.in
  src/cmd/flux-account.py
  src/cmd/flux_account_update_fshare.cpp
  src/fairness/print_hierarchy/flux_account_shares.cpp
  t/t1007-flux-account.t
Labels: merge-when-passing, improvement

#166 NEWS.md: add release notes for `v0.11.0`
  NEWS.md
Labels: documentation

#173 build: drop ax_python_devel.m4
  config/ax_python_devel.m4
  configure.ac
Labels: merge-when-passing

#175 doc: add LLNL code release number to README
  README.md
Labels: documentation, merge-when-passing, low priority

#167 flux-account-priority-update: change `bulk_update` method
  src/cmd/flux-account-priority-update.py
  src/plugins/mf_priority.cpp
  t/Makefile.am
  t/scripts/send_payload.py
  t/t1001-mf-priority-basic.t
  t/t1002-mf-priority-small-no-tie.t
  t/t1003-mf-priority-small-tie.t
  t/t1004-mf-priority-small-tie-all.t
  t/t1005-max-jobs-limits.t
  t/t1008-mf-priority-update.t
Labels: merge-when-passing, improvement, medium priority
