Repository flux-framework/flux-accounting, pull requests merged in 2022-12, with the labels that each got.

#300 github: change Ubuntu version for python-lint check
  .github/workflows/main.yml
Labels: merge-when-passing, bug-fix

#302 testsuite: do not assume queues default to stopped
  t/t1013-mf-priority-queues.t
Labels: merge-when-passing

#299 edit-bank: add ability to edit parent bank
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/test/test_bank_subcommands.py
  src/cmd/flux-account.py
  t/Makefile.am
  t/expected/print_hierarchy/after_parent_bank_change.expected
  t/expected/print_hierarchy/before_parent_bank_change.expected
  t/t1000-print-hierarchy.t
Labels: new feature, merge-when-passing

#303 testsuite: stop all queues with --all option
  t/rc/rc1-job
  t/t1013-mf-priority-queues.t
Labels: merge-when-passing

#304 NEWS: add release notes for `v0.21.0`
  NEWS.md
Labels: documentation, merge-when-passing
