Repository flux-framework/flux-accounting, pull requests merged in 2022-10, with the labels that each got.

#278 testsuite: adjust queue tests for flux-core changes
  configure.ac
  t/sharness.d/flux-sharness.sh
  t/t1013-mf-priority-queues.t
Labels: merge-when-passing

#281 plugin: disable queue validation on an unknown queue, no configured "default" queue
  src/plugins/mf_priority.cpp
  t/t1013-mf-priority-queues.t
  t/t1018-mf-priority-disable-entry.t
Labels: merge-when-passing, improvement

#286 plugin: change default values of "DNE" entry to allow multiple jobs to be submitted
  src/plugins/mf_priority.cpp
  t/t1014-mf-priority-dne.t
Labels: merge-when-passing, bug-fix

#287 plugin: change install location
  src/plugins/Makefile.am
Labels: merge-when-passing, improvement

#282 NEWS: add release notes for v0.20.0
  NEWS.md
Labels: documentation, merge-when-passing

#288 `update-db`: use tempfile module for temporary flux-accounting DB during upgrade
  src/cmd/flux-account-update-db.py
  t/t1017-update-db.t
Labels: merge-when-passing, bug-fix

#289 NEWS: add release notes for v0.20.1
  NEWS.md
Labels: documentation, merge-when-passing

#277 add-user: add bank validation
  src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
  src/bindings/python/fluxacct/accounting/test/test_user_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  t/t1007-flux-account.t
Labels: merge-when-passing, bug-fix
