Repository flux-framework/flux-accounting, pull requests merged in 2023-07, with the labels that each got.

#361 flux-accounting DB: update schema version
  src/bindings/python/fluxacct/accounting/__init__.py.in
  src/cmd/flux-account-service.py
  t/Makefile.am
  t/expected/test_dbs/FluxAccountingv0-25-0.db
Labels: merge-when-passing

#362 NEWS: add release notes for v0.26.0
  NEWS.md
Labels: documentation, merge-when-passing

#366 .cpp: add config.h include to source code
  src/fairness/account/account.cpp
  src/fairness/reader/data_reader_base.cpp
  src/fairness/reader/data_reader_db.cpp
  src/fairness/reader/test/data_reader_db_test01.cpp
  src/fairness/weighted_tree/test/weighted_tree_load.cpp
  src/fairness/weighted_tree/test/weighted_tree_test01.cpp
  src/fairness/weighted_tree/weighted_tree.cpp
  src/fairness/weighted_tree/weighted_walk.cpp
  src/fairness/writer/data_writer_base.cpp
  src/fairness/writer/data_writer_db.cpp
  src/fairness/writer/data_writer_stdout.cpp
  src/fairness/writer/test/data_writer_db_test01.cpp
  src/plugins/mf_priority.cpp
Labels: merge-when-passing, improvement

#367 t: reorganize `t1007-flux-account.t` into multiple sharness tests
  t/Makefile.am
  t/expected/flux_account/A_bank.expected
  t/t1007-flux-account-users.t
  t/t1007-flux-account.t
  t/t1023-flux-account-banks.t
  t/t1024-flux-account-queues.t
  t/t1025-flux-account-projects.t
  t/t1026-flux-account-perms.t
Labels: merge-when-passing, improvement, testing

#363 build: add `make deb` target for test packaging
  Makefile.am
  debian/README.Debian
  debian/README.source
  debian/compat
  debian/control
  debian/copyright
  debian/rules
  debian/source/format
  scripts/debbuild.sh
Labels: merge-when-passing
