Repository flux-framework/flux-accounting, pull requests merged in 2023-09, with the labels that each got.

#373 t: add valgrind folder to flux-accounting
  config/ax_valgrind.m4
  configure.ac
  src/test/checks_run.sh
  t/Makefile.am
  t/t5000-valgrind.t
  t/valgrind/valgrind-workload.sh
  t/valgrind/valgrind.supp
  t/valgrind/workload.d/job
Labels: merge-when-passing, testing

#374 python: rename `rows` variable to something more descriptive
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/job_archive_interface.py
  src/bindings/python/fluxacct/accounting/project_subcommands.py
  src/bindings/python/fluxacct/accounting/queue_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
Labels: merge-when-passing, improvement

#378 plugin: check for `FLUX_JOB_STATE_NEW` in `validate_cb()`
  src/plugins/mf_priority.cpp
  t/Makefile.am
  t/t1027-mf-priority-issue376.t
Labels: new feature, merge-when-passing

#375 ci: update github actions `main.yml` file
  .github/workflows/main.yml
Labels: merge-when-passing

#379 NEWS: add release notes for `v0.27.0`
  NEWS.md
Labels: documentation, merge-when-passing

#382 `edit-user`: fix default values for optional args
  src/cmd/flux-account.py
Labels: merge-when-passing, bug-fix

#383 testsuite: load content module in rc scripts
  t/rc/rc1-job
  t/rc/rc1-kvs
  t/rc/rc3-job
  t/rc/rc3-kvs
Labels: merge-when-passing

#387 ci: remove `upload-tarball` step from workflow
  .github/workflows/main.yml
Labels: merge-when-passing, testing, bug-fix

#386 plugin: improve check of internal user/bank map in `job.validate`
  src/plugins/mf_priority.cpp
  t/Makefile.am
  t/t1028-mf-priority-issue385.t
Labels: merge-when-passing, bug-fix

#388 plugin: move queue priority assignment to `job.new` callback
  src/plugins/mf_priority.cpp
Labels: merge-when-passing, improvement

#301 plugin: record bank name to jobspec when user submits under default bank
  src/plugins/mf_priority.cpp
  t/Makefile.am
  t/t1029-mf-priority-default-bank.t
Labels: merge-when-passing, improvement

#392 testsuite: allow sharness tests to be run by hand
  t/sharness.d/flux-accounting.sh
Labels: merge-when-passing

#389 plugin: add queue update validation
  src/plugins/mf_priority.cpp
  t/Makefile.am
  t/t1030-mf-priority-update-queue.t
Labels: new feature, merge-when-passing

#395 `view-bank`: fix `-t` option for a sub bank with users in it
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  t/Makefile.am
  t/expected/flux_account/E_bank.expected
  t/t1023-flux-account-banks.t
Labels: merge-when-passing, bug-fix
