Repository flux-framework/flux-accounting, pull requests merged in 2024-07, with the labels that each got.

#460 job archive interface: clean up a couple helper functions
  src/bindings/python/fluxacct/accounting/job_archive_interface.py
Labels: merge-when-passing, improvement

#461 NEWS: add release notes for `v0.34.0`
  NEWS.md
Labels: documentation, merge-when-passing

#462 t: move python unit tests to `t/python/` directory
  src/bindings/python/fluxacct/accounting/Makefile.am
  src/bindings/python/fluxacct/accounting/test/test_example.py
  src/bindings/python/fluxacct/accounting/test/test_project_subcommands.py
  t/Makefile.am
  t/python/t1001_db.py
  t/python/t1002_user_cmds.py
  t/python/t1003_bank_cmds.py
  t/python/t1004_queue_cmds.py
  t/python/t1005_project_cmds.py
  t/python/t1006_job_archive.py
Labels: merge-when-passing, testing

#463 python: clean job-archive interface code
  src/bindings/python/fluxacct/accounting/Makefile.am
  src/bindings/python/fluxacct/accounting/job_usage_calculation.py
  src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
  src/cmd/flux-account-service.py
  t/python/t1006_job_archive.py
Labels: merge-when-passing, improvement

#465 `conf.update`: add missing bracket in format string
  src/plugins/mf_priority.cpp
Labels: merge-when-passing, bug-fix

#467 testsuite: fix on systems with flux-accounting already installed
  t/sharness.d/flux-accounting.sh
Labels: merge-when-passing

#466 NEWS: add release notes for `v0.35.0`
  NEWS.md
Labels: documentation, merge-when-passing

#468 python: change function descriptions to follow docstring convention
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/job_usage_calculation.py
  src/bindings/python/fluxacct/accounting/project_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
Labels: documentation, merge-when-passing, improvement

#470 python: convert more function descriptions to docstring format
  src/bindings/python/fluxacct/accounting/job_usage_calculation.py
  src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
Labels: documentation, merge-when-passing, improvement

#471 src: remove `flux_account_shares.cpp` in favor of just using `-t` option with `view-bank`
  doc/guide/accounting-guide.rst
  src/Makefile.am
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  src/cmd/flux_account_shares.cpp
  t/Makefile.am
  t/expected/pop_db/db_hierarchy_base.expected
  t/expected/pop_db/db_hierarchy_new_users.expected
  t/expected/print_hierarchy/small_no_tie.txt
  t/expected/print_hierarchy/small_no_tie_parsable.txt
  t/expected/print_hierarchy/small_tie.txt
  t/expected/print_hierarchy/small_tie_all.txt
  t/expected/print_hierarchy/small_tie_all_parsable.txt
  t/expected/print_hierarchy/small_tie_parsable.txt
  t/expected/update_fshare/post_fshare_update.expected
  t/expected/update_fshare/pre_fshare_update.expected
  t/t1000-print-hierarchy.t
  t/t1006-update-fshare.t
  t/t1009-pop-db.t
  t/t1011-job-archive-interface.t
  t/t1016-export-db.t
  t/t1036-hierarchy-small-no-tie-db.t
  t/t1037-hierarchy-small-tie-db.t
  t/t1038-hierarchy-small-tie-all-db.t
Labels: merge-when-passing, improvement
