Repository flux-framework/flux-accounting, pull requests merged in 2024-05, with the labels that each got.

#447 t: update descriptions of sharness tests
  t/t1011-job-archive-interface.t
  t/t1016-export-db.t
  t/t1022-mf-priority-issue346.t
  t/t1027-mf-priority-issue376.t
  t/t1028-mf-priority-issue385.t
Labels: merge-when-passing, testing

#357 flux-accounting: add a local job-archive
  src/Makefile.am
  src/bindings/python/fluxacct/accounting/create_db.py
  src/bindings/python/fluxacct/accounting/job_archive_interface.py
  src/bindings/python/fluxacct/accounting/test/test_create_db.py
  src/bindings/python/fluxacct/accounting/test/test_job_archive_interface.py
  src/cmd/flux-account-fetch-job-records.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/Makefile.am
  t/expected/job_usage/no_jobs.expected
  t/expected/job_usage/post_update1.expected
  t/expected/job_usage/post_update2.expected
  t/expected/job_usage/pre_update.expected
  t/t1010-update-usage.t
  t/t1011-job-archive-interface.t
  t/t1017-update-db.t
  t/t1026-flux-account-perms.t
Labels: new feature, merge-when-passing

#446 repo: create a `doc` folder, add flux-accounting guide
  doc/guide/accounting-guide.rst
Labels: documentation, new feature, merge-when-passing

#449 testsuite: enable guest access to testexec
  t/t1001-mf-priority-basic.t
  t/t1002-mf-priority-small-no-tie.t
  t/t1003-mf-priority-small-tie.t
  t/t1004-mf-priority-small-tie-all.t
  t/t1005-max-jobs-limits.t
  t/t1008-mf-priority-update.t
  t/t1013-mf-priority-queues.t
  t/t1015-mf-priority-urgency.t
  t/t1019-mf-priority-info-fetch.t
  t/t1020-mf-priority-issue262.t
  t/t1021-mf-priority-issue332.t
  t/t1022-mf-priority-issue346.t
  t/t1027-mf-priority-issue376.t
  t/t1028-mf-priority-issue385.t
  t/t1029-mf-priority-default-bank.t
  t/t1030-mf-priority-update-queue.t
  t/t1031-mf-priority-issue406.t
  t/t1032-mf-priority-update-bank.t
  t/t1033-mf-priority-update-job.t
Labels: merge-when-passing

#448 NEWS: add release notes for v0.32.0
  NEWS.md
Labels: documentation, merge-when-passing

#453 database: update schema version
  src/bindings/python/fluxacct/accounting/__init__.py.in
Labels: merge-when-passing

#393 testsuite: change check for specific job states
  t/t1005-max-jobs-limits.t
  t/t1011-job-archive-interface.t
  t/t1012-mf-priority-load.t
  t/t1013-mf-priority-queues.t
  t/t1014-mf-priority-dne.t
  t/t1018-mf-priority-disable-entry.t
  t/t1019-mf-priority-info-fetch.t
  t/t1020-mf-priority-issue262.t
  t/t1022-mf-priority-issue346.t
  t/t1028-mf-priority-issue385.t
Labels: merge-when-passing, testing

#454 testsuite: replace `flux job cancel` --> `flux cancel`
  t/t1001-mf-priority-basic.t
  t/t1005-max-jobs-limits.t
  t/t1011-job-archive-interface.t
  t/t1012-mf-priority-load.t
  t/t1013-mf-priority-queues.t
  t/t1014-mf-priority-dne.t
  t/t1018-mf-priority-disable-entry.t
  t/t1019-mf-priority-info-fetch.t
  t/t1020-mf-priority-issue262.t
  t/t1022-mf-priority-issue346.t
  t/t1027-mf-priority-issue376.t
  t/t1028-mf-priority-issue385.t
  t/t1029-mf-priority-default-bank.t
  t/t1030-mf-priority-update-queue.t
  t/t1031-mf-priority-issue406.t
  t/t1032-mf-priority-update-bank.t
  t/t1033-mf-priority-update-job.t
  t/t1034-mf-priority-config.t
Labels: merge-when-passing, testing
