Repository flux-framework/flux-accounting, pull requests merged in 2024-12, with the labels that each got.

#545 NEWS: add release notes for `v0.40.0`
  NEWS.md
Labels: documentation, merge-when-passing

#546 testsuite: pull in valgrind suppression from core
  t/valgrind/valgrind.supp
Labels: merge-when-passing

#547 github: fix ubuntu version for `"python-format"` action
  .github/workflows/main.yml
Labels: merge-when-passing, testing

#550 doc: add section on configuring queue permissions
  doc/guide/accounting-guide.rst
Labels: documentation, merge-when-passing

#525 python: create new `BankFormatter` subclass, restructure `view-bank` to use new class
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/formatter.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/Makefile.am
  t/expected/flux_account/A_bank.expected
  t/expected/flux_account/D_bank.expected
  t/expected/flux_account/E_bank.expected
  t/expected/flux_account/F_bank_tree.expected
  t/expected/flux_account/F_bank_users.expected
  t/expected/flux_account/full_hierarchy.expected
  t/expected/flux_account/root_bank.expected
  t/expected/pop_db/db_hierarchy_base.expected
  t/expected/pop_db/db_hierarchy_new_users.expected
  t/expected/print_hierarchy/small_no_tie.txt
  t/expected/print_hierarchy/small_tie.txt
  t/expected/print_hierarchy/small_tie_all.txt
  t/expected/update_fshare/post_fshare_update.expected
  t/expected/update_fshare/pre_fshare_update.expected
  t/python/t1008_banks_output.py
  t/t1023-flux-account-banks.t
  t/t1036-hierarchy-small-no-tie-db.t
  t/t1037-hierarchy-small-tie-db.t
  t/t1038-hierarchy-small-tie-all-db.t
Labels: merge-when-passing, improvement, low priority

#527 `view-user`: create new `AssociationFormatter` subclass for viewing associations
  src/bindings/python/fluxacct/accounting/formatter.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/Makefile.am
  t/python/t1009_users_output.py
  t/t1007-flux-account-users.t
  t/t1011-job-archive-interface.t
  t/t1023-flux-account-banks.t
  t/t1025-flux-account-projects.t
Labels: merge-when-passing, improvement, low priority, commands

#548 testsuite: add longer test descriptions for some of the more complex test scenarios
  t/t1001-mf-priority-basic.t
  t/t1002-mf-priority-small-no-tie.t
  t/t1003-mf-priority-small-tie.t
  t/t1004-mf-priority-small-tie-all.t
  t/t1005-max-jobs-limits.t
  t/t1008-mf-priority-update.t
  t/t1011-job-archive-interface.t
  t/t1012-mf-priority-load.t
  t/t1013-mf-priority-queues.t
  t/t1015-mf-priority-urgency.t
  t/t1019-mf-priority-info-fetch.t
  t/t1020-mf-priority-issue262.t
  t/t1021-mf-priority-issue332.t
  t/t1022-mf-priority-issue346.t
  t/t1027-mf-priority-issue376.t
  t/t1028-mf-priority-issue385.t
  t/t1029-mf-priority-default-bank.t
  t/t1030-mf-priority-update-queue.t
  t/t1031-mf-priority-issue406.t
  t/t1032-mf-priority-update-bank.t
  t/t1033-mf-priority-update-job.t
Labels: merge-when-passing, testing
