Repository flux-framework/flux-accounting, pull requests merged in 2024-10, with the labels that each got.

#492 `job.state.inactive`: add `return -1` to exception
  src/plugins/mf_priority.cpp
Labels: merge-when-passing, improvement, plugin

#493 NEWS: add release notes for `v0.38.0`
  NEWS.md
Labels: documentation, merge-when-passing

#494 `view-user`: make "parsable" spelling consistent
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/t1007-flux-account-users.t
  t/t1036-hierarchy-small-no-tie-db.t
  t/t1037-hierarchy-small-tie-db.t
  t/t1038-hierarchy-small-tie-all-db.t
Labels: merge-when-passing, improvement

#495 projects: fix unit tests for project subcommands, `--projects` reset capability
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  t/python/t1005_project_cmds.py
  t/t1025-flux-account-projects.t
Labels: merge-when-passing, improvement

#496 command suite: add new `list-projects` command
  src/bindings/python/fluxacct/accounting/project_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/t1025-flux-account-projects.t
Labels: new feature, merge-when-passing

#499 plugin: add callback prefixes to exception messages
  src/plugins/mf_priority.cpp
Labels: merge-when-passing, plugin

#500 doc: add note about manually loading plugin
  doc/guide/accounting-guide.rst
Labels: documentation, merge-when-passing

#501 doc: add ReadTheDocs support for flux-accounting
  .readthedocs.yaml
  doc/conf.py
  doc/index.rst
Labels: documentation, new feature, merge-when-passing

#504 ci: add spellchecker to flux-accounting
  .github/workflows/main.yml
  .typos.toml
  config/ax_flux_core.m4
  doc/test/spell.en.pws
  doc/test/spellcheck
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/job_usage_calculation.py
  src/bindings/python/fluxacct/accounting/project_subcommands.py
  src/cmd/flux-account-priority-update.py
  src/cmd/flux-account-service.py
  src/plugins/accounting.hpp
  src/plugins/mf_priority.cpp
  src/plugins/test/accounting_test01.cpp
  src/test/checks_run.sh
  t/t1005-max-jobs-limits.t
  t/t1025-flux-account-projects.t
  t/t1033-mf-priority-update-job.t
Labels: documentation, new feature, merge-when-passing

#505 guide: add note about configuring factor weights
  doc/guide/accounting-guide.rst
Labels: documentation, merge-when-passing

#509 `add-bank`: add a check when adding a root bank
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  t/Makefile.am
  t/python/t1002_user_cmds.py
  t/python/t1003_bank_cmds.py
  t/t1042-issue508.t
Labels: merge-when-passing, bug-fix

#506 doc: add "Database Administration" section, update README to point to docs site
  README.md
  doc/components/database-administration.rst
  doc/index.rst
  doc/index_man.rst
  doc/man5/index.rst
Labels: documentation, merge-when-passing

#510 doc: reorganize top-level site, add License and Support page
  doc/guide/images/lgplv3-147x51.png
  doc/guide/support.rst
  doc/index.rst
Labels: documentation, merge-when-passing

#511 `.gitignore`: add built docs, sharness test results
  .gitignore
Labels: merge-when-passing, improvement

#513 doc: add priority equation to accounting guide
  doc/guide/accounting-guide.rst
Labels: merge-when-passing

#516 fetch-job-records: set `max_entries=0`
  src/cmd/flux-account-fetch-job-records.py
Labels: merge-when-passing, bug-fix

#514 `view-user --parsable`: improve output formatting
  src/bindings/python/fluxacct/accounting/user_subcommands.py
Labels: merge-when-passing, improvement

#518 t: skip t1011 if job-archive module not detected, add new tests for `fetch-job-records`
  t/t1011-job-archive-interface.t
Labels: merge-when-passing, testing

#512 `flux-account.py`: get rid of dictionary initialization
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
Labels: merge-when-passing, improvement, low priority

#521 `__init__.py`: fix formatting of constants
  src/bindings/python/fluxacct/accounting/__init__.py.in
  src/bindings/python/fluxacct/accounting/create_db.py
  src/cmd/flux-account-fetch-job-records.py
  src/cmd/flux-account-priority-update.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account-update-db.py
  src/cmd/flux-account.py
Labels: merge-when-passing, low priority, bug-fix

#520 python: add `AccountingFormatter` class, SQLite utility file
  src/bindings/python/fluxacct/accounting/Makefile.am
  src/bindings/python/fluxacct/accounting/__init__.py.in
  src/bindings/python/fluxacct/accounting/formatter.py
  src/bindings/python/fluxacct/accounting/sql_util.py
  t/Makefile.am
  t/python/t1007_formatter.py
Labels: new feature, merge-when-passing

#522 `view_jobs()`: adjust helper function to actually return a string
  src/bindings/python/fluxacct/accounting/jobs_table_subcommands.py
  src/cmd/flux-account.py
  t/python/t1006_job_archive.py
Labels: merge-when-passing, improvement, low priority
