Repository flux-framework/flux-accounting, pull requests merged in 2025-03, with the labels that each got.

#592 doc: add health/sanity checklist for flux-accounting
  doc/guide/sanity-checklist.rst
  doc/index.rst
Labels: documentation, merge-when-passing

#594 `apply_decay_factor ()`: fix iteration through usage periods, actually `commit` SQL statements
  src/bindings/python/fluxacct/accounting/job_usage_calculation.py
  t/python/t1006_job_archive.py
Labels: merge-when-passing, bug-fix

#597 cmd: add new `list-users` command
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/Makefile.am
  t/t1051-list-users.t
Labels: new feature, merge-when-passing

#491 plugin: add enforcement of max running jobs limit for a queue per-association
  src/bindings/python/fluxacct/accounting/__init__.py.in
  src/bindings/python/fluxacct/accounting/create_db.py
  src/bindings/python/fluxacct/accounting/queue_subcommands.py
  src/cmd/flux-account-priority-update.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  src/plugins/accounting.cpp
  src/plugins/accounting.hpp
  src/plugins/mf_priority.cpp
  src/plugins/test/accounting_test01.cpp
  t/Makefile.am
  t/t1052-mf-priority-queue-limits.t
Labels: new feature, merge-when-passing, plugin

#600 `view-*`/`list-*` commands: add `-o/--format` optional argument
  src/bindings/python/fluxacct/accounting/bank_subcommands.py
  src/bindings/python/fluxacct/accounting/formatter.py
  src/bindings/python/fluxacct/accounting/queue_subcommands.py
  src/bindings/python/fluxacct/accounting/user_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/t1007-flux-account-users.t
  t/t1023-flux-account-banks.t
  t/t1024-flux-account-queues.t
  t/t1051-list-users.t
Labels: new feature, merge-when-passing, commands

#602 bindings: add `ProjectFormatter` subclass, `-o/--format` options to `view-project`/`list-projects`
  src/bindings/python/fluxacct/accounting/formatter.py
  src/bindings/python/fluxacct/accounting/project_subcommands.py
  src/cmd/flux-account-service.py
  src/cmd/flux-account.py
  t/t1025-flux-account-projects.t
Labels: merge-when-passing, improvement, commands

#603 mf_priority: update jj library from flux-core
  src/plugins/jj.cpp
Labels: merge-when-passing
